### ISSUE TITLE
Any plans to PR upstream?

### ISSUE THREAD

**Issue by JoseExposito** [janeasystems/node-mobile-react-demo#2]
Hi all,

First at all, I love this prove of concept and what you did.
I can not wait to see how you achieved this once you release the project source :)

Not sure if it is too early to ask this, but, do you have any plans to send this changes upstream?
It'd be fantastic if MS could support iOS officially and very beneficial for the entire Node.js community.

Also, do you have a road map that I can check to get more information about the project?
I couldn't find any information in https://github.com/janeasystems/nodejs-mobile and I'd love to know more and get involved.

Thanks in advance,
Jose

**Comment by orangemocha** [comment]
@JoseExposito I can't speak for Microsoft, but from what I know at the moment they have more pressing priorities than maintaining an iOS port. Until that changes, we are hoping to fill the void ourselves, with the help of the community.

> I can not wait to see how you achieved this once you release the project source :)

We are going to have some interesting news by next week. Stay tuned :)

And after those news we can have a more meaningful conversation about project roadmap. We'd certainly welcome your involvement.

**Comment by JoseExposito** [comment]
Excellent news, thanks for the update.

Looking forward to the announcement next week 🎉

**Comment by orangemocha** [comment]
@JoseExposito 

Today we published our work for bringing Node.js to Android and iOS, including React Native and Cordova plugins, and all the source code.

Announcement: http://www.janeasystems.com/blog/announcing-node-js-mobile-apps-true-node-js-runtime-android-ios/
Project website: https://code.janeasystems.com/nodejs-mobile
Main GitHub repo: https://github.com/janeasystems/nodejs-mobile

:champagne:

**Comment by JoseExposito** [comment]
Thank you very much for the heads up @orangemocha 

This is excellent news, congratulations to all the team!!

**Comment by orangemocha** [comment]
Closing this issue now. Let us know if you have any more feedback.
