### ISSUE TITLE
internal module not found while build node with enable-static

### ISSUE THREAD

**Issue by tommyZZM** [janeasystems/node-mobile-react-demo#3]
hi, i m trying to embedding node-chakracore as a static library. ( with the node/node-chakracore remotes )

but i got issue while embedding `libnode.a` on calling `node::Start(int argc, char** argv)`

https://github.com/nodejs/node-chakracore/issues/409

maybe all inernal module is not loaded? what is the best way to slove this?

```
bootstrap_node.js:489
  const ContextifyScript = process.binding('contextify').ContextifyScript;
  ^
 
Error: No such module: contextify
   at Anonymous function (bootstrap_node.js:489:3)
Program ended with exit code: 6
```

some related issue:
https://github.com/nodejs/node/issues/686#issuecomment-74559487
https://github.com/electron/node/issues/4

**Comment by jaimecbernardo** [comment]
Hi @tommyZZM ,
Thanks for opening the issue.

This repository is for a demo only. Have you checked our project to run Node.js on mobile operating systems? https://github.com/janeasystems/nodejs-mobile

In our iOS build process, Node.js is built as a static library as well by the helper script and then the Xcode project uses it to build libnode.framework https://github.com/janeasystems/nodejs-mobile#building-the-ios-framework-library-on-macos

We made some changes to make this possible, like exporting the symbols for native module registering when Node.js is build as a static library as well: https://github.com/janeasystems/nodejs-mobile/commit/7ee73e96c2a89914d025f4d217faef32b370fbf6

Then, you have to make sure your build system doesn't strip these symbols when building your application, which differs depending on what you're using to build your application.

If you're trying to do it for Android or iOS, please consider checking our project https://github.com/janeasystems/nodejs-mobile 

Further issues should be opened there. I'd also ask you to open the issue there if you want to discuss it further.

I'm closing this issue.
